### ISSUE TITLE
Upsert functionality

### ISSUE THREAD

**Issue by jesseditson** [arjunmehta/node-georedis#2]
Hey, thanks for this awesome library.

I was wondering about the difference between `addLocation` and `updateLocation` - in my application, I am looking to do an "upsert" - just to add or update depending on if the location already exists. Does one or both of these methods already expose this functionality? And if not, is there a way to avoid doing a `get` and then an `update` or `add` depending on the existence of the value returned by get?

**Comment by arjunmehta** [comment]
Hey there @jesseditson,

The difference for `addLocation` and `updateLocation` is purely semantic. They both do the same thing in reality, that is an "upsert" (as you call it).

That is, if the location doesn't exist it will be added, and if it does it will be updated, no matter which method you use. So take your pick :)

You can see more in the source [here](https://github.com/arjunmehta/node-georedis/blob/master/main.js#L78-L80).

The reason for this behavior is because Redis automatically does that by default for the commands we're using ([ZADD](http://redis.io/commands/zadd) for emulation mode and [GEOADD](http://redis.io/commands/geoadd) for native mode).

**Comment by jesseditson** [comment]
Ah, fantastic! Thanks so much for the clarification, and thanks again for the lib!

**Comment by arjunmehta** [comment]
Thank you! Let me know if you encounter any strange behaviour. It was a recent rewrite (to 3.0.0) so I'm on edge :)

**Comment by jesseditson** [comment]
Absolutely! I'm working it in to a project now, I'll be sure to file anything I run across here!
